name: build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Theos
        id: cache-theos
        uses: actions/cache@v4
        with:
          path: $HOME/theos
          key: theos-${{ runner.os }}-${{ hashFiles('.github/workflows/build.yml') }}

      - name: Install Theos (if missing)
        if: steps.cache-theos.outputs.cache-hit != 'true'
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos

      - name: Setup env & iOS SDK link
        shell: bash
        run: |
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "PATH=$HOME/theos/bin:$PATH" >> $GITHUB_ENV
          SDK_PATH=$(xcrun --sdk iphoneos --show-sdk-path)
          mkdir -p "$HOME/theos/sdks"
          ln -sf "$SDK_PATH" "$HOME/theos/sdks/iPhoneOS.sdk"

      - name: Build tweak
        env:
          THEOS: ${{ env.THEOS }}
        run: |
          make clean package FINALPACKAGE=1

      - name: Extract dylib and plist
        run: |
          mkdir -p out
          DEB=$(ls packages/*.deb | head -n1)
          dpkg-deb -x "$DEB" extract
          # عدّل المسار إذا اختلف اسم ملفك
          cp extract/Library/MobileSubstrate/DynamicLibraries/TTTranslateKit.dylib out/
          cp extract/Library/MobileSubstrate/DynamicLibraries/TTTranslateKit.plist out/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TTTranslateKit-artifact
          path: out/*

