name: build-tttranslatekit
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps & Theos
        run: |
          brew install ldid make git dpkg || true
          git clone https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          # استخدم iOS SDK الجاهز في بيئة GitHub
          SDK_PATH="$(xcrun --sdk iphoneos --show-sdk-path)"
          mkdir -p "$HOME/theos/sdks"
          ln -s "$SDK_PATH" "$HOME/theos/sdks/$(basename "$SDK_PATH")" || true
          ln -s "$SDK_PATH" "$HOME/theos/sdks/iPhoneOS.sdk" || true

      - name: Build tweak
        # ملفاتك في جذر الريبو، لذلك نبني من هنا
        working-directory: .
        env:
          THEOS: ${{ env.THEOS }}
        run: |
          make clean package FINALPACKAGE=1

      - name: Extract dylib
        run: |
          mkdir -p out
          DEB=$(ls packages/*.deb | head -n1)
          dpkg-deb -x "$DEB" extract
          cp extract/Library/MobileSubstrate/DynamicLibraries/TTTranslateKit.dylib out/
          cp TTTranslateKit.plist out/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TTTranslateKit-dylib
          path: out/*
