name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Theos
        id: cache-theos
        uses: actions/cache@v4
        with:
          path: $HOME/theos
          key: theos-${{ runner.os }}-${{ hashFiles('.github/workflows/build.yml') }}

      - name: Install Theos (if missing)
        if: steps.cache-theos.outputs.cache-hit != 'true'
        run: git clone --recursive https://github.com/theos/theos.git $HOME/theos

      - name: Setup env & iOS SDK link
        shell: bash
        run: |
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "PATH=$HOME/theos/bin:$PATH" >> $GITHUB_ENV
          SDK_PATH=$(xcrun --sdk iphoneos --show-sdk-path)
          mkdir -p "$HOME/theos/sdks"
          ln -sf "$SDK_PATH" "$HOME/theos/sdks/$(basename "$SDK_PATH")"
          ln -sf "$SDK_PATH" "$HOME/theos/sdks/iPhoneOS.sdk"

      - name: Install packaging tools (no dpkg -i)
        continue-on-error: true
        run: |
          brew update
          brew install dpkg ldid || true
          ldid -v || true
          dpkg-deb --version || true

      - name: Build tweak (release)
        env:
          THEOS: ${{ env.THEOS }}
        run: make clean package FINALPACKAGE=1

      - name: Upload dylib (release)
        uses: actions/upload-artifact@v4
        with:
          name: TTTranslateKit-dylib
          path: packages/**/*.dylib

      - name: Upload deb (release)
        uses: actions/upload-artifact@v4
        with:
          name: TTTranslateKit-deb
          path: packages/*.deb

      - name: Build tweak (debug with alert)
        env:
          THEOS: ${{ env.THEOS }}
        run: make clean package FINALPACKAGE=1 DEBUG=1

      - name: Upload dylib (debug)
        uses: actions/upload-artifact@v4
        with:
          name: TTTranslateKit-dylib-debug
          path: packages/**/*.dylib
