name: build-tttranslatekit
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps & Theos
        run: |
          brew install ldid make git dpkg || true
          git clone https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

          # استخدم iOS SDK المثبّت مع Xcode على جهاز الماك السحابي
          SDK_PATH="$(xcrun --sdk iphoneos --show-sdk-path)"
          mkdir -p "$HOME/theos/sdks"
          # اربط مسار الـ SDK ليتوافق مع شكل الأسماء التي يتوقعها Theos
          ln -s "$SDK_PATH" "$HOME/theos/sdks/$(basename "$SDK_PATH")" || true
          ln -s "$SDK_PATH" "$HOME/theos/sdks/iPhoneOS.sdk" || true

      - name: Build tweak
        working-directory: TTTranslateKit/inject
        env:
          THEOS: ${{ env.THEOS }}
        run: |
          make clean package FINALPACKAGE=1

      - name: Extract dylib
        run: |
          mkdir -p out
          DEB=$(ls TTTranslateKit/inject/packages/*.deb | head -n1)
          dpkg-deb -x "$DEB" extract
          cp extract/Library/MobileSubstrate/DynamicLibraries/TTTranslateKit.dylib out/
          cp TTTranslateKit/inject/TTTranslateKit.plist out/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TTTranslateKit-dylib
          path: out/*
